
export const GET_POSTS = 'GET_POSTS';
export const GET_SELECTED_POST = 'GET_SELECTED_POST';

export const SAVE_POST = 'SAVE_POST';
export const GET_ARTIST = 'GET_ARTIST';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const UPDATE_USER = "UPDATE_USER";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ERRORS = "GET_ERRORS";

export const GET_REC_POSTS = "GET_REC_POSTS";
export const GET_REC_SONGS = "GET_REC_SONGS";

export const GET_CURRENTLY_LISTENING_SONG = 'GET_CURRENTLY_LISTENING_SONG';
export const GET_USERS_RECENT_LISTENING_ACTIVITY = "GET_USERS_RECENT_LISTENING_ACTIVITY"


